name: Update Packagist on Tag

on:
  push:
    tags:
      - "v*" # Match tags starting with 'v' (e.g., v1.0.0, v2.1.3)

jobs:
  update_packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: "8.1" # Adjust to your preferred PHP version

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Update Packagist
        run: |
          composer config --global --auth github-token "$GITHUB_TOKEN"
          composer package publish --repository=packagist --repository-url=https://packagist.org
